<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $departments = [
            ['dpt_id' => '1111', 'division_id' => null, 'department' => 'PROD1 (GA)',                 'level' => 0, 'parent' => 1110, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => '2025-09-26 03:27:37'],
            ['dpt_id' => '1112', 'division_id' => null, 'department' => 'PROD1 (MTN)',                'level' => 0, 'parent' => 1110, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1113', 'division_id' => null, 'department' => 'PROD1 (PCE)',                'level' => 0, 'parent' => 1110, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1114', 'division_id' => null, 'department' => 'PROD1 (PPC)',                'level' => 0, 'parent' => 1110, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1115', 'division_id' => null, 'department' => 'PROD1 (WH JT)',              'level' => 0, 'parent' => 1110, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1116', 'division_id' => null, 'department' => 'PROD1 (HRD)',                'level' => 0, 'parent' => 1110, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1131', 'division_id' => null, 'department' => 'PROD2 (GA)',                 'level' => 0, 'parent' => 1130, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1132', 'division_id' => null, 'department' => 'PROD2 (MTN)',                'level' => 0, 'parent' => 1130, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1133', 'division_id' => null, 'department' => 'PROD2 (MTN)',                'level' => 0, 'parent' => 1130, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1134', 'division_id' => null, 'department' => 'PROD2 (PCE ASSY)',           'level' => 0, 'parent' => 1130, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1135', 'division_id' => null, 'department' => 'PROD2 (PCE)',                'level' => 0, 'parent' => 1130, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1136', 'division_id' => null, 'department' => 'PROD2 (PPC ASSY)',           'level' => 0, 'parent' => 1130, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1137', 'division_id' => null, 'department' => 'PROD2 (PPC)',                'level' => 0, 'parent' => 1130, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1138', 'division_id' => null, 'department' => 'PROD2 (WH JT ASSY)',         'level' => 0, 'parent' => 1130, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1139', 'division_id' => null, 'department' => 'PROD2 (WH JT)',              'level' => 0, 'parent' => 1130, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1140', 'division_id' => null, 'department' => 'PROD2 (HRD)',                'level' => 0, 'parent' => 1130, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1151', 'division_id' => null, 'department' => 'PROD3 (GA)',                 'level' => 0, 'parent' => 1150, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1152', 'division_id' => null, 'department' => 'PROD3 (MTN ASSY)',           'level' => 0, 'parent' => 1150, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1153', 'division_id' => null, 'department' => 'PROD3 (MTN)',                'level' => 0, 'parent' => 1150, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1154', 'division_id' => null, 'department' => 'PROD3 (PCE ASSY)',           'level' => 0, 'parent' => 1150, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1155', 'division_id' => null, 'department' => 'PROD3 (PCE)',                'level' => 0, 'parent' => 1150, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1156', 'division_id' => null, 'department' => 'PROD3 (PPC ASSY)',           'level' => 0, 'parent' => 1150, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1157', 'division_id' => null, 'department' => 'PROD3 (PPC)',                'level' => 0, 'parent' => 1150, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1158', 'division_id' => null, 'department' => 'PROD3 (WH JT ASSY)',         'level' => 0, 'parent' => 1150, 'alloc' => 'ASSY 2W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1159', 'division_id' => null, 'department' => 'PROD3 (WH JT)',              'level' => 0, 'parent' => 1150, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1160', 'division_id' => null, 'department' => 'PROD3 (HRD)',                'level' => 0, 'parent' => 1150, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1211', 'division_id' => null, 'department' => 'PROD4 (GA)',                 'level' => 0, 'parent' => 1210, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1212', 'division_id' => null, 'department' => 'PROD4 (MTN GRINDING)',       'level' => 0, 'parent' => 1210, 'alloc' => 'ALL GRINDING',  'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1213', 'division_id' => null, 'department' => 'PROD4 (MTN PLATING)',        'level' => 0, 'parent' => 1210, 'alloc' => 'ALL PLATING',   'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1214', 'division_id' => null, 'department' => 'PROD4 (MTN)',                'level' => 0, 'parent' => 1210, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1215', 'division_id' => null, 'department' => 'PROD4 (PCE GRINDING)',       'level' => 0, 'parent' => 1210, 'alloc' => 'ALL GRINDING',  'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1216', 'division_id' => null, 'department' => 'PROD4 (PCE PLATING)',        'level' => 0, 'parent' => 1210, 'alloc' => 'ALL PLATING',   'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1217', 'division_id' => null, 'department' => 'PROD4 (PCE)',                'level' => 0, 'parent' => 1210, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1218', 'division_id' => null, 'department' => 'PROD4 (PPC GRINDING)',       'level' => 0, 'parent' => 1210, 'alloc' => 'ALL GRINDING',  'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1219', 'division_id' => null, 'department' => 'PROD4 (PPC PLATING)',        'level' => 0, 'parent' => 1210, 'alloc' => 'ALL PLATING',   'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1220', 'division_id' => null, 'department' => 'PROD4 (PPC)',                'level' => 0, 'parent' => 1210, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1221', 'division_id' => null, 'department' => 'PROD4 (WH JT GRINDING)',     'level' => 0, 'parent' => 1210, 'alloc' => 'ALL GRINDING',  'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1222', 'division_id' => null, 'department' => 'PROD4 (WH JT PLATING)',      'level' => 0, 'parent' => 1210, 'alloc' => 'ALL PLATING',   'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1223', 'division_id' => null, 'department' => 'PROD4 (WH JT)',              'level' => 0, 'parent' => 1210, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1224', 'division_id' => null, 'department' => 'PROD4 (HRD)',                'level' => 0, 'parent' => 1210, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1231', 'division_id' => null, 'department' => 'PROD5 (GA)',                 'level' => 0, 'parent' => 1230, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1232', 'division_id' => null, 'department' => 'PROD5 (MTN ALL ASSY)',       'level' => 0, 'parent' => 1230, 'alloc' => 'ASSY 4W',       'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1233', 'division_id' => null, 'department' => 'PROD5 (MTN ASSY GAS)',       'level' => 0, 'parent' => 1230, 'alloc' => 'ASSY GAS 4W',   'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1234', 'division_id' => null, 'department' => 'PROD5 (MTN ASSY OIL)',       'level' => 0, 'parent' => 1230, 'alloc' => 'ASSY OIL 4W',   'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1235', 'division_id' => null, 'department' => 'PROD5 (MTN)',                'level' => 0, 'parent' => 1230, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1236', 'division_id' => null, 'department' => 'PROD5 (PCE ASSY)',           'level' => 0, 'parent' => 1230, 'alloc' => 'ASSY',          'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1237', 'division_id' => null, 'department' => 'PROD5 (PCE)',                'level' => 0, 'parent' => 1230, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1238', 'division_id' => null, 'department' => 'PROD5 (PPC ASSY)',           'level' => 0, 'parent' => 1230, 'alloc' => 'ASSY',          'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1239', 'division_id' => null, 'department' => 'PROD5 (PPC)',                'level' => 0, 'parent' => 1230, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1240', 'division_id' => null, 'department' => 'PROD5 (WH JT ASSY)',         'level' => 0, 'parent' => 1230, 'alloc' => 'ASSY',          'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1241', 'division_id' => null, 'department' => 'PROD5 (WH JT)',              'level' => 0, 'parent' => 1230, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1242', 'division_id' => null, 'department' => 'PROD5 (HRD)',                'level' => 0, 'parent' => 1230, 'alloc' => 'GEN',           'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1311', 'division_id' => null, 'department' => 'PPC & INVENTORY',            'level' => 0, 'parent' => 1310, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1321', 'division_id' => null, 'department' => 'MAINTENANCE',                'level' => 0, 'parent' => 1320, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1331', 'division_id' => null, 'department' => 'WH FG',                      'level' => 0, 'parent' => 1330, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1332', 'division_id' => null, 'department' => 'WH CKDRM',                   'level' => 0, 'parent' => 1330, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1333', 'division_id' => null, 'department' => 'WH JIGTOOLS',                'level' => 0, 'parent' => 1330, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1334', 'division_id' => null, 'department' => 'WH PACKAGING',               'level' => 0, 'parent' => 1330, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1341', 'division_id' => null, 'department' => 'PCE 2W',                     'level' => 0, 'parent' => 1340, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1351', 'division_id' => null, 'department' => 'PCE 4W',                     'level' => 0, 'parent' => 1350, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1361', 'division_id' => null, 'department' => 'PCE',                        'level' => 0, 'parent' => 1360, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1411', 'division_id' => null, 'department' => 'PROD SYSTEM',                'level' => 0, 'parent' => 1410, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '2111', 'division_id' => null, 'department' => 'PDE 2W',                     'level' => 0, 'parent' => 2110, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '2121', 'division_id' => null, 'department' => 'PDE 4W',                     'level' => 0, 'parent' => 2120, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '3111', 'division_id' => null, 'department' => 'CQE 2W',                     'level' => 0, 'parent' => 3110, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '3121', 'division_id' => null, 'department' => 'QA',                         'level' => 0, 'parent' => 3120, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '3131', 'division_id' => null, 'department' => 'CQE 4W',                     'level' => 0, 'parent' => 3130, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4111', 'division_id' => null, 'department' => 'HRD & IR',                   'level' => 0, 'parent' => 4110, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4131', 'division_id' => null, 'department' => 'GA',                         'level' => 0, 'parent' => 4130, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4141', 'division_id' => null, 'department' => 'MIS',                        'level' => 0, 'parent' => 4140, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4151', 'division_id' => null, 'department' => 'CPC',                        'level' => 0, 'parent' => 4150, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4161', 'division_id' => null, 'department' => 'PROCUREMENT',                'level' => 0, 'parent' => 4160, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4171', 'division_id' => null, 'department' => 'GEN PURCHASE',               'level' => 0, 'parent' => 4170, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4181', 'division_id' => null, 'department' => 'VDD',                        'level' => 0, 'parent' => 4180, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4211', 'division_id' => null, 'department' => 'EHS',                        'level' => 0, 'parent' => 4210, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '4311', 'division_id' => null, 'department' => 'COMMITTEE',                  'level' => 0, 'parent' => 4310, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '5111', 'division_id' => null, 'department' => 'MARKETING',                  'level' => 0, 'parent' => 5110, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '6111', 'division_id' => null, 'department' => 'FIN & ACC',                  'level' => 0, 'parent' => 6110, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '6121', 'division_id' => null, 'department' => 'PLAN & BUDGET',              'level' => 0, 'parent' => 6120, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '7111', 'division_id' => null, 'department' => 'BOARD OF DIRECTOR',          'level' => 0, 'parent' => 7110, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '7211', 'division_id' => null, 'department' => 'TECHNICAL ADVISOR',          'level' => 0, 'parent' => 7210, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
            ['dpt_id' => '1118', 'division_id' => null, 'department' => 'PROD2',                      'level' => 0, 'parent' => 1110, 'alloc' => 'GEN',           'status' => 1, 'created_at' => '2025-07-11 07:29:01', 'updated_at' => '2025-09-15 01:09:24'],
            ['dpt_id' => '1201', 'division_id' => null, 'department' => 'INI DEPT',                   'level' => 0, 'parent' => 1000, 'alloc' => '0',             'status' => 1, 'created_at' => '2025-07-17 05:11:36', 'updated_at' => '2025-09-15 04:18:02'],
            ['dpt_id' => '4221', 'division_id' => null, 'department' => 'TDD',                        'level' => 0, 'parent' => 4220, 'alloc' => null,            'status' => 1, 'created_at' => null, 'updated_at' => null],
        ];

        DB::table('departments')->insert($departments);
    }
}